.TH groovyc "1" "December 2007"
.SH NAME
groovyc \- compiler for groovy source files
.SH DESCRIPTION
usage: groovyc [options] <source-files>
options:
.TP
\fB\-\-classpath\fR <path>
Specify where to find the class files.
.TP
\fB\-d\fR <arg>
Specify where to place generated class files.
.TP
\fB\-e\fR,\-\-exception
Print stack trace on error.
.TP
\fB\-\-encoding\fR <encoding>
Specify the encoding of the user class files.
.HP
\fB\-F\fR <flag>
.TP
\fB\-h\fR,\-\-help
Print a synopsis of standard options.
.TP
\fB\-j\fR,\-\-jointCompilation
Attach javac compiler to compile .java files.
.HP
\fB\-J\fR <property=value>
.TP
\fB\-\-sourcepath\fR <path>
Specify where to find the source files.
.HP
\fB\-\-temp\fR <temp>
.TP
\fB\-v\fR,\-\-version
Print the version.
.SS "options:"
.TP
\fB\-\-classpath\fR <path>
Specify where to find the class files.
.TP
\fB\-d\fR <arg>
Specify where to place generated class files.
.TP
\fB\-e\fR,\-\-exception
Print stack trace on error.
.TP
\fB\-\-encoding\fR <encoding>
Specify the encoding of the user class files.
.HP
\fB\-F\fR <flag>
.TP
\fB\-h\fR,\-\-help
Print a synopsis of standard options.
.TP
\fB\-j\fR,\-\-jointCompilation
Attach javac compiler to compile .java files.
.HP
\fB\-J\fR <property=value>
.TP
\fB\-\-sourcepath\fR <path>
Specify where to find the source files.
.HP
\fB\-\-temp\fR <temp>
.TP
\fB\-v\fR,\-\-version
Print the version.
.SH "SEE ALSO"
.BR groovy (1)
.SH AUTHOR
This manual page was generated using help2man and edited by Varun
Hiremath <varun@debian.org>, for the Debian project (but may be used
by others).
